# coding:utf-8
# features

nolog = ['user_id','item_id', 'buy']
	

factor_features = [
		
	"user_item_last2day_cart_nobuy",
	"user_item_last3day_cart_nobuy",
	"cat_lastday_buy_again",
	"cat_lastday_cart_nobuy",
	"cat_lastday_click_nobuy",
	"cat_lastday_star_nobuy",
	"item_geo_4",
	"item_geo_9",
	"item_geo_f",
	"item_geo_m",
	"item_geo_t",
	"item_lastday_buy_again",
	"item_lastday_cart_nobuy",
	"item_lastday_click_nobuy",
	"item_lastday_star_nobuy",
	"user_cat_lastday_buy_again",
	"user_cat_lastday_cart_nobuy",
	"user_cat_lastday_click_nobuy",
	"user_cat_lastday_star_nobuy",
	"user_geo_4",
#	"user_geo_5",
	"user_geo_9",
	"user_geo_b",
	"user_geo_f",
#	"user_geo_i",
	"user_geo_m",
	"user_geo_o",
	"user_geo_t",
	"user_geo_v",
	"user_in_hot_pos_1",
	"user_in_hot_pos_2",
	"user_in_hot_pos_3",
	"user_in_hot_pos_4",
	"user_in_hot_pos_5",
	"user_in_hot_pos_6",
	"user_in_hot_pos_7",
	"user_item_buy_again",
	"user_item_cart_nobuy",
	"user_item_click_nobuy",
	"user_item_lastday_buy_again",
	"user_item_lastday_cart_nobuy",
	"user_item_lastday_click_nobuy",
	"user_item_lastday_star_nobuy",
	"user_item_star_nobuy",

	"user_is_robot",
	"item_share_major",
	"user_die",


	]
	
signed_log_features = [
		"user_cat_aveThreeDayDelta_add_car",
	"user_cat_aveThreeDayDelta_buy",
	"user_cat_aveThreeDayDelta_click",
	"user_cat_aveThreeDayDelta_star",

	"user_item_aveThreeDayDelta_add_car",
	"user_item_aveThreeDayDelta_buy",
	"user_item_aveThreeDayDelta_click",
	"user_item_aveThreeDayDelta_star",

	]
	
log_features = [
		
	"cat_add_car",
	"cat_add_star",
	"cat_before_halfmonth_add_car",
	"cat_before_halfmonth_buy",
	"cat_before_halfmonth_click",
	"cat_before_halfmonth_star",
	"cat_buy_count",
	"cat_buy_user_number",
	"cat_click_count",
	"cat_halfmonth_add_car",
	"cat_halfmonth_buy",
	"cat_halfmonth_click",
	"cat_halfmonth_star",
	"cat_lastday_add_car",
	"cat_lastday_buy",
	"cat_lastday_click",
	"cat_lastday_star",
	"cat_lastweek_add_car",
	"cat_lastweek_buy",
	"cat_lastweek_click",
	"cat_lastweek_star",
	"geo_users_number",
	"item_added_car",
	"item_added_start",
	"item_before_halfmonth_add_car",
	"item_before_halfmonth_buy",
	"item_before_halfmonth_click",
	"item_before_halfmonth_star",
	"item_buy_count",
	"item_buy_user_number",
	"item_click_count",
	"item_halfmonth_add_car",
	"item_halfmonth_buy",
	"item_halfmonth_click",
	"item_halfmonth_star",
	"item_lastday_add_car",
	"item_lastday_buy",
	"item_lastday_click",
	"item_lastday_count",
	"item_lastday_star",
	"item_lastweek_add_car",
	"item_lastweek_buy",
	"item_lastweek_click",
	"item_lastweek_star",
	"user_action_count",
	"user_add_car",
	"user_add_star",
	"user_buy_cat_number",
	"user_buy_count",
	"user_buy_item_number",

	"user_cat_before_halfmonth_add_car",
	"user_cat_before_halfmonth_buy",
	"user_cat_before_halfmonth_click",
	"user_cat_before_halfmonth_star",
	"user_cat_count",
	"user_cat_halfmonth_add_car",
	"user_cat_halfmonth_buy",
	"user_cat_halfmonth_click",
	"user_cat_halfmonth_star",
	"user_cat_lastday_add_cart",
	"user_cat_lastday_add_star",
	"user_cat_lastday_buy",
	"user_cat_lastday_count",
	"user_cat_lastweek_add_car",
	"user_cat_lastweek_buy",
	"user_cat_lastweek_click",
	"user_cat_lastweek_star",
	"user_item_before_halfmonth_add_car",
	"user_item_before_halfmonth_buy",
	"user_item_before_halfmonth_click",
	"user_item_before_halfmonth_star",
	"user_item_buy",

	"user_item_count",

	"user_item_halfmonth_add_car",
	"user_item_halfmonth_buy",
	"user_item_halfmonth_click",
	"user_item_halfmonth_star",
	"user_item_lastday_add_cart",
	"user_item_lastday_add_star",
	"user_item_lastday_buy",
	"user_item_lastday_count",
	"user_item_lasttime",
	"user_item_lastweek_add_car",
	"user_item_lastweek_buy",
	"user_item_lastweek_click",
	"user_item_lastweek_star",

	"user_lastday_add_cart",
	"user_lastday_add_star",
	"user_lastday_buy",
	"user_lastday_count",
	"usergeo_item_before_lastday_buy",
	"usergeo_item_before_lastday_cart",
	"usergeo_item_before_lastday_click",
	"usergeo_item_before_lastday_star",
	"usergeo_item_lastday_buy",
	"usergeo_item_lastday_cart",
	"usergeo_item_lastday_click",
	"usergeo_item_lastday_star",

	"user_item_last7day_buy",
	"user_item_last14day_buy",
	"user_item_last21day_buy",

	"user_item_last2day_add_car",
	"user_item_last2day_buy",
	"user_item_last2day_click",
	"user_item_last2day_star",
	"user_item_last3day_add_car",
	"user_item_last3day_buy",
	"user_item_last3day_click",
	"user_item_last3day_star",

	
	"user_item_1212_add_car",
	"user_item_1212_buy",
	"user_item_1212_click",
	"user_item_1212_star",


	
	"user_active_days",
	"item_active_days",
	"cat_active_days",
	"user_lastweek_active_days",
	"item_lastweek_active_days",
	"cat_lastweek_active_days",
	"user_item_active_days",
	"user_item_lastweek_active_days",
	"user_cat_active_days",
	"user_cat_lastweek_active_days",
	"user_lastday_active_hours",
	"item_lastday_active_hours",
	"user_item_lastday_active_hours",
	"cat_lastday_active_hours",
	"user_cat_lastday_active_hours",
	"user_last_active_time",
	"item_last_active_time",
	"cat_last_active_time",
	"user_item_last_active_time",
	"user_cat_last_active_time"
	
	

	]
	
linear_features = [
	"user_item_geo_distance",
	"user_convert_rate",
	"item_convert_rate",
]

allfeatures = [
"cat_add_car",
"cat_add_star",
"cat_before_halfmonth_add_car",
"cat_before_halfmonth_buy",
"cat_before_halfmonth_click",
"cat_before_halfmonth_star",
"cat_buy_count",
"cat_buy_user_number",
"cat_click_count",
"cat_halfmonth_add_car",
"cat_halfmonth_buy",
"cat_halfmonth_click",
"cat_halfmonth_star",
"cat_lastday_add_car",
"cat_lastday_buy",
"cat_lastday_buy_again",
"cat_lastday_cart_nobuy",
"cat_lastday_click",
"cat_lastday_click_nobuy",
"cat_lastday_star",
"cat_lastday_star_nobuy",
"cat_lastweek_add_car",
"cat_lastweek_buy",
"cat_lastweek_click",
"cat_lastweek_star",
"geo_users_number",
"item_added_car",
"item_added_start",
"item_before_halfmonth_add_car",
"item_before_halfmonth_buy",
"item_before_halfmonth_click",
"item_before_halfmonth_star",
"item_buy_count",
"item_buy_user_number",
"item_click_count",
"item_geo_4",
"item_geo_9",
"item_geo_f",
"item_geo_m",
"item_geo_t",
"item_halfmonth_add_car",
"item_halfmonth_buy",
"item_halfmonth_click",
"item_halfmonth_star",
"item_lastday_add_car",
"item_lastday_buy",
"item_lastday_buy_again",
"item_lastday_cart_nobuy",
"item_lastday_click",
"item_lastday_click_nobuy",
"item_lastday_count",
"item_lastday_star",
"item_lastday_star_nobuy",
"item_lastweek_add_car",
"item_lastweek_buy",
"item_lastweek_click",
"item_lastweek_star",
"user_action_count",
"user_add_car",
"user_add_star",
"user_buy_cat_number",
"user_buy_count",
"user_buy_item_number",
"user_cat_aveThreeDayDelta_add_car",
"user_cat_aveThreeDayDelta_buy",
"user_cat_aveThreeDayDelta_click",
"user_cat_aveThreeDayDelta_star",
"user_cat_before_halfmonth_add_car",
"user_cat_before_halfmonth_buy",
"user_cat_before_halfmonth_click",
"user_cat_before_halfmonth_star",
"user_cat_count",
"user_cat_halfmonth_add_car",
"user_cat_halfmonth_buy",
"user_cat_halfmonth_click",
"user_cat_halfmonth_star",
"user_cat_lastday_add_cart",
"user_cat_lastday_add_star",
"user_cat_lastday_buy",
"user_cat_lastday_buy_again",
"user_cat_lastday_cart_nobuy",
"user_cat_lastday_click_nobuy",
"user_cat_lastday_count",
"user_cat_lastday_star_nobuy",
"user_cat_lastweek_add_car",
"user_cat_lastweek_buy",
"user_cat_lastweek_click",
"user_cat_lastweek_star",
"user_geo_4",
"user_geo_5",
"user_geo_9",
"user_geo_b",
"user_geo_f",
"user_geo_i",
"user_geo_m",
"user_geo_o",
"user_geo_t",
"user_geo_v",
"user_in_hot_pos_1",
"user_in_hot_pos_2",
"user_in_hot_pos_3",
"user_in_hot_pos_4",
"user_in_hot_pos_5",
"user_in_hot_pos_6",
"user_in_hot_pos_7",
"user_item_1212_add_car",
"user_item_1212_buy",
"user_item_1212_click",
"user_item_1212_star",
"user_item_aveThreeDayDelta_add_car",
"user_item_aveThreeDayDelta_buy",
"user_item_aveThreeDayDelta_click",
"user_item_aveThreeDayDelta_star",
"user_item_before_halfmonth_add_car",
"user_item_before_halfmonth_buy",
"user_item_before_halfmonth_click",
"user_item_before_halfmonth_star",
"user_item_buy",
"user_item_buy_again",
"user_item_cart_nobuy",
"user_item_click_nobuy",
"user_item_count",
"user_item_geo_distance",
"user_item_halfmonth_add_car",
"user_item_halfmonth_buy",
"user_item_halfmonth_click",
"user_item_halfmonth_star",
"user_item_last14day_buy",
"user_item_last21day_buy",
"user_item_last2day_add_car",
"user_item_last2day_buy",
"user_item_last2day_click",
"user_item_last2day_star",
"user_item_last3day_add_car",
"user_item_last3day_buy",
"user_item_last3day_click",
"user_item_last3day_star",
"user_item_last7day_buy",
"user_item_lastday_add_cart",
"user_item_lastday_add_star",
"user_item_lastday_buy",
"user_item_lastday_buy_again",
"user_item_lastday_cart_nobuy",
"user_item_lastday_click_nobuy",
"user_item_lastday_count",
"user_item_lastday_star_nobuy",
"user_item_lasttime",
"user_item_lastweek_add_car",
"user_item_lastweek_buy",
"user_item_lastweek_click",
"user_item_lastweek_star",
"user_item_star_nobuy",
"user_lastday_add_cart",
"user_lastday_add_star",
"user_lastday_buy",
"user_lastday_count",
"usergeo_item_before_lastday_buy",
"usergeo_item_before_lastday_cart",
"usergeo_item_before_lastday_click",
"usergeo_item_before_lastday_star",
"usergeo_item_lastday_buy",
"usergeo_item_lastday_cart",
"usergeo_item_lastday_click",
"usergeo_item_lastday_star",

# 合成特征
"user_item_last2day_cart_nobuy",
"user_item_last3day_cart_nobuy",
"user_convert_rate",
"item_convert_rate",
"user_is_robot",
"item_share_major",
"user_die",


# 时间特征
"user_active_days",
"item_active_days",
"cat_active_days",
"user_lastweek_active_days",
"item_lastweek_active_days",
"cat_lastweek_active_days",
"user_item_active_days",
"user_item_lastweek_active_days",
"user_cat_active_days",
"user_cat_lastweek_active_days",
"user_lastday_active_hours",
"item_lastday_active_hours",
"user_item_lastday_active_hours",
"cat_lastday_active_hours",
"user_cat_lastday_active_hours",
"user_last_active_time",
"item_last_active_time",
"cat_last_active_time",
"user_item_last_active_time",
"user_cat_last_active_time"
]